/* =========================================================
   公司主檔
   ========================================================= */
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/* =========================================================
   客戶主檔
   ========================================================= */
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,

    -- EXPENSE：支出
    -- ADVANCE：代墊
    default_request_category VARCHAR(20),

    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_customers_request_category
        CHECK (
            default_request_category IS NULL
            OR default_request_category IN ('EXPENSE', 'ADVANCE')
        )
);


/* =========================================================
   費用類型主檔
   管理員可以新增或停用費用類型
   ========================================================= */
CREATE TABLE expense_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,

    /*
      MANUAL：人工輸入金額
      MEAL：人數 × 天數 × 餐數 × 單價
      QUANTITY_PRICE：數量 × 單價
      TRAVEL：交通費
      CONFIRMATION：函證郵資
    */
    calculation_type VARCHAR(30) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_expense_types_calculation_type
        CHECK (
            calculation_type IN (
                'MANUAL',
                'MEAL',
                'QUANTITY_PRICE',
                'TRAVEL',
                'CONFIRMATION'
            )
        )
);


/* =========================================================
   費用單價歷史

   例如：
   餐費／DEFAULT／80
   郵資／NORMAL_MAIL／8
   郵資／REGISTERED_MAIL／28
   郵資／EXPRESS_REGISTERED／35
   ========================================================= */
CREATE TABLE expense_price_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_type_id BIGINT NOT NULL,

    price_code VARCHAR(50) NOT NULL DEFAULT 'DEFAULT',
    price_name VARCHAR(100) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,

    effective_from DATE NOT NULL,
    effective_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_expense_price_settings_expense_type
        FOREIGN KEY (expense_type_id)
        REFERENCES expense_types (id),

    CONSTRAINT chk_expense_price_settings_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_expense_price_settings_period
        CHECK (
            effective_to IS NULL
            OR effective_to >= effective_from
        )
);


/*
  同一個費用類型、同一種價格代碼，
  同時間只能有一筆尚未結束的有效價格。
*/
CREATE UNIQUE INDEX uq_expense_price_settings_current
    ON expense_price_settings (expense_type_id, price_code)
    WHERE active = TRUE
      AND effective_to IS NULL;


/* =========================================================
   請款主檔
   ========================================================= */
CREATE TABLE payment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    request_no VARCHAR(50) NOT NULL UNIQUE,

    applicant_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,

    /*
      送出時記錄當下主管。
      未送出的草稿可以是 NULL。
    */
    supervisor_snapshot_id BIGINT,

    company_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,

    request_category VARCHAR(20) NOT NULL,
    reason TEXT NOT NULL,

    /*
      DRAFT
      PENDING_MANAGER
      PENDING_CASHIER
      APPROVED
      REJECTED_CLOSED
    */
    approval_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

    /*
      UNPAID
      PAID
    */
    payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',

    total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,

    submitted_at TIMESTAMP WITH TIME ZONE,
    approved_at TIMESTAMP WITH TIME ZONE,
    approved_by_id BIGINT,

    rejected_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,

    paid_at TIMESTAMP WITH TIME ZONE,
    paid_by_id BIGINT,
    payment_method VARCHAR(30),
    payment_reference VARCHAR(100),
    payment_note TEXT,

    /*
      日後對應 JPA @Version，
      防止兩個人同時修改同一張請款單。
    */
    version BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_requests_applicant
        FOREIGN KEY (applicant_id)
        REFERENCES app_users (id),

    CONSTRAINT fk_payment_requests_department
        FOREIGN KEY (department_id)
        REFERENCES departments (id),

    CONSTRAINT fk_payment_requests_supervisor_snapshot
        FOREIGN KEY (supervisor_snapshot_id)
        REFERENCES app_users (id),

    CONSTRAINT fk_payment_requests_company
        FOREIGN KEY (company_id)
        REFERENCES companies (id),

    CONSTRAINT fk_payment_requests_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id),

    CONSTRAINT fk_payment_requests_approved_by
        FOREIGN KEY (approved_by_id)
        REFERENCES app_users (id),

    CONSTRAINT fk_payment_requests_paid_by
        FOREIGN KEY (paid_by_id)
        REFERENCES app_users (id),

    CONSTRAINT chk_payment_requests_category
        CHECK (
            request_category IN ('EXPENSE', 'ADVANCE')
        ),

    CONSTRAINT chk_payment_requests_approval_status
        CHECK (
            approval_status IN (
                'DRAFT',
                'PENDING_MANAGER',
                'PENDING_CASHIER',
                'APPROVED',
                'REJECTED_CLOSED'
            )
        ),

    CONSTRAINT chk_payment_requests_payment_status
        CHECK (
            payment_status IN ('UNPAID', 'PAID')
        ),

    CONSTRAINT chk_payment_requests_total_amount
        CHECK (total_amount >= 0),

    /*
      只有已核准案件才能登記為已付款。
    */
    CONSTRAINT chk_payment_requests_paid_requires_approval
        CHECK (
            payment_status <> 'PAID'
            OR approval_status = 'APPROVED'
        ),

    /*
      已付款時必須有付款人與付款時間。
    */
    CONSTRAINT chk_payment_requests_paid_information
        CHECK (
            payment_status <> 'PAID'
            OR (
                paid_at IS NOT NULL
                AND paid_by_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_payment_requests_payment_method
        CHECK (
            payment_method IS NULL
            OR payment_method IN (
                'CASH',
                'BANK_TRANSFER',
                'OTHER'
            )
        )
);


/* =========================================================
   請款明細
   ========================================================= */
CREATE TABLE payment_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_request_id BIGINT NOT NULL,
    expense_type_id BIGINT NOT NULL,

    /*
      使用哪一筆後台單價設定，可為 NULL。
      人工輸入金額時不一定有價格設定。
    */
    price_setting_id BIGINT,

    description TEXT,

    people_count INTEGER,
    days INTEGER,
    quantity NUMERIC(14, 2),
    unit_price NUMERIC(14, 2),

    /*
      函證來回郵資可填 2，
      一般項目通常填 1。
    */
    multiplier NUMERIC(10, 2) NOT NULL DEFAULT 1,

    amount NUMERIC(14, 2) NOT NULL,

    /*
      保存不同費用才有的欄位，例如：
      {
        "startLocation": "台北",
        "endLocation": "新竹",
        "stampSize": "LARGE",
        "mailType": "REGISTERED_MAIL"
      }
    */
    extra_data JSONB NOT NULL DEFAULT '{}'::JSONB,

    sort_order INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_request_items_request
        FOREIGN KEY (payment_request_id)
        REFERENCES payment_requests (id),

    CONSTRAINT fk_payment_request_items_expense_type
        FOREIGN KEY (expense_type_id)
        REFERENCES expense_types (id),

    CONSTRAINT fk_payment_request_items_price_setting
        FOREIGN KEY (price_setting_id)
        REFERENCES expense_price_settings (id),

    CONSTRAINT chk_payment_request_items_people_count
        CHECK (
            people_count IS NULL
            OR people_count > 0
        ),

    CONSTRAINT chk_payment_request_items_days
        CHECK (
            days IS NULL
            OR days > 0
        ),

    CONSTRAINT chk_payment_request_items_quantity
        CHECK (
            quantity IS NULL
            OR quantity > 0
        ),

    CONSTRAINT chk_payment_request_items_unit_price
        CHECK (
            unit_price IS NULL
            OR unit_price >= 0
        ),

    CONSTRAINT chk_payment_request_items_multiplier
        CHECK (multiplier > 0),

    CONSTRAINT chk_payment_request_items_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payment_request_items_sort_order
        CHECK (sort_order > 0)
);


/* =========================================================
   簽核及付款操作歷程
   ========================================================= */
CREATE TABLE approval_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_request_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,

    /*
      SUBMIT
      MANAGER_APPROVE
      MANAGER_REJECT
      CASHIER_APPROVE
      CASHIER_REJECT
      PAYMENT_RECORDED
    */
    action VARCHAR(30) NOT NULL,

    from_approval_status VARCHAR(30),
    to_approval_status VARCHAR(30),

    from_payment_status VARCHAR(20),
    to_payment_status VARCHAR(20),

    comment TEXT,
    acted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_approval_histories_request
        FOREIGN KEY (payment_request_id)
        REFERENCES payment_requests (id),

    CONSTRAINT fk_approval_histories_actor
        FOREIGN KEY (actor_id)
        REFERENCES app_users (id),

    CONSTRAINT chk_approval_histories_action
        CHECK (
            action IN (
                'SUBMIT',
                'MANAGER_APPROVE',
                'MANAGER_REJECT',
                'CASHIER_APPROVE',
                'CASHIER_REJECT',
                'PAYMENT_RECORDED'
            )
        )
);


/* =========================================================
   請款附件
   先建資料表，檔案上傳 API 後面再實作。
   ========================================================= */
CREATE TABLE payment_request_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_request_id BIGINT NOT NULL,
    uploaded_by_id BIGINT NOT NULL,

    /*
      INVOICE：發票
      RECEIPT：收據
      REQUEST_PROOF：其他請款證明
      PAYMENT_PROOF：付款證明
      OTHER：其他
    */
    attachment_type VARCHAR(30) NOT NULL,

    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_request_attachments_request
        FOREIGN KEY (payment_request_id)
        REFERENCES payment_requests (id),

    CONSTRAINT fk_payment_request_attachments_uploaded_by
        FOREIGN KEY (uploaded_by_id)
        REFERENCES app_users (id),

    CONSTRAINT chk_payment_request_attachments_type
        CHECK (
            attachment_type IN (
                'INVOICE',
                'RECEIPT',
                'REQUEST_PROOF',
                'PAYMENT_PROOF',
                'OTHER'
            )
        ),

    CONSTRAINT chk_payment_request_attachments_file_size
        CHECK (file_size > 0)
);


/* =========================================================
   常用查詢索引
   ========================================================= */
CREATE INDEX idx_payment_requests_applicant
    ON payment_requests (applicant_id);

CREATE INDEX idx_payment_requests_customer
    ON payment_requests (customer_id);

CREATE INDEX idx_payment_requests_approval_status
    ON payment_requests (approval_status);

CREATE INDEX idx_payment_requests_payment_status
    ON payment_requests (payment_status);

CREATE INDEX idx_payment_requests_supervisor_pending
    ON payment_requests (
        supervisor_snapshot_id,
        approval_status
    );

CREATE INDEX idx_payment_requests_created_at
    ON payment_requests (created_at);

CREATE INDEX idx_payment_request_items_request
    ON payment_request_items (payment_request_id);

CREATE INDEX idx_approval_histories_request
    ON approval_histories (
        payment_request_id,
        acted_at
    );

CREATE INDEX idx_payment_request_attachments_request
    ON payment_request_attachments (payment_request_id);