CREATE TABLE app_user_credentials (
    user_id BIGINT PRIMARY KEY,

    password_hash VARCHAR(255) NOT NULL,

    password_changed_at TIMESTAMP WITH TIME ZONE,

    last_login_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_app_user_credentials_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (id)
);

CREATE TABLE app_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    role_code VARCHAR(50) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_app_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (id),

    CONSTRAINT uq_app_user_roles_user_role
        UNIQUE (user_id, role_code),

    CONSTRAINT chk_app_user_roles_role_code
        CHECK (
            role_code IN (
                'CASHIER',
                'PAYMENT_OPERATOR'
            )
        )
);

CREATE INDEX idx_app_user_roles_user_id
ON app_user_roles (user_id);

CREATE INDEX idx_app_user_roles_role_code
ON app_user_roles (role_code);
