CREATE TABLE master_data_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id UUID NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    actor_id BIGINT NOT NULL,
    actor_username_snapshot VARCHAR(100) NOT NULL,
    actor_display_name_snapshot VARCHAR(100) NOT NULL,
    before_data JSONB,
    after_data JSONB NOT NULL,
    before_version BIGINT,
    after_version BIGINT NOT NULL,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_master_data_audit_logs_actor
        FOREIGN KEY (actor_id)
        REFERENCES app_users (id),

    CONSTRAINT chk_master_data_audit_logs_target_id
        CHECK (target_id > 0),

    CONSTRAINT chk_master_data_audit_logs_actor_username
        CHECK (BTRIM(actor_username_snapshot) <> ''),

    CONSTRAINT chk_master_data_audit_logs_actor_display_name
        CHECK (BTRIM(actor_display_name_snapshot) <> ''),

    CONSTRAINT chk_master_data_audit_logs_target_type
        CHECK (
            target_type IN (
                'EXPENSE_TYPE',
                'EXPENSE_PRICE_SETTING'
            )
        ),

    CONSTRAINT chk_master_data_audit_logs_action
        CHECK (
            action IN (
                'EXPENSE_TYPE_CREATE',
                'EXPENSE_TYPE_RENAME',
                'EXPENSE_TYPE_ACTIVATE',
                'EXPENSE_TYPE_DEACTIVATE',
                'EXPENSE_PRICE_CREATE',
                'EXPENSE_PRICE_REPLACE'
            )
        ),

    CONSTRAINT chk_master_data_audit_logs_action_target
        CHECK (
            (
                target_type = 'EXPENSE_TYPE'
                AND action IN (
                    'EXPENSE_TYPE_CREATE',
                    'EXPENSE_TYPE_RENAME',
                    'EXPENSE_TYPE_ACTIVATE',
                    'EXPENSE_TYPE_DEACTIVATE'
                )
            )
            OR (
                target_type = 'EXPENSE_PRICE_SETTING'
                AND action IN (
                    'EXPENSE_PRICE_CREATE',
                    'EXPENSE_PRICE_REPLACE'
                )
            )
        ),

    CONSTRAINT chk_master_data_audit_logs_before_data_object
        CHECK (
            before_data IS NULL
            OR jsonb_typeof(before_data) = 'object'
        ),

    CONSTRAINT chk_master_data_audit_logs_after_data_object
        CHECK (jsonb_typeof(after_data) = 'object'),

    CONSTRAINT chk_master_data_audit_logs_versions
        CHECK (
            (before_version IS NULL OR before_version >= 0)
            AND after_version >= 0
        ),

    CONSTRAINT chk_master_data_audit_logs_before_pair
        CHECK ((before_data IS NULL) = (before_version IS NULL)),

    CONSTRAINT chk_master_data_audit_logs_reason
        CHECK (
            reason IS NULL
            OR BTRIM(reason) <> ''
        ),

    CONSTRAINT chk_master_data_audit_logs_snapshot_shape
        CHECK (
            (
                action IN ('EXPENSE_TYPE_CREATE', 'EXPENSE_PRICE_CREATE')
                AND before_data IS NULL
                AND before_version IS NULL
                AND after_version = 0
            )
            OR (
                action IN (
                    'EXPENSE_TYPE_RENAME',
                    'EXPENSE_TYPE_ACTIVATE',
                    'EXPENSE_TYPE_DEACTIVATE'
                )
                AND before_data IS NOT NULL
                AND before_version IS NOT NULL
                AND after_version = before_version + 1
            )
            OR (
                action = 'EXPENSE_PRICE_REPLACE'
                AND (
                    (
                        before_data IS NULL
                        AND before_version IS NULL
                        AND after_version = 0
                    )
                    OR (
                        before_data IS NOT NULL
                        AND before_version IS NOT NULL
                        AND after_version = before_version + 1
                    )
                )
            )
        )
);

CREATE INDEX idx_master_data_audit_logs_target
    ON master_data_audit_logs (target_type, target_id, created_at, id);

CREATE INDEX idx_master_data_audit_logs_operation_id
    ON master_data_audit_logs (operation_id);

CREATE INDEX idx_master_data_audit_logs_actor
    ON master_data_audit_logs (actor_id, created_at);

CREATE OR REPLACE FUNCTION prevent_master_data_audit_log_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'master_data_audit_logs is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_master_data_audit_logs_append_only
    BEFORE UPDATE OR DELETE
    ON master_data_audit_logs
    FOR EACH ROW
    EXECUTE FUNCTION prevent_master_data_audit_log_mutation();
